### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by bertho-zero**

### CODE REVIEW

**Comment by eddyystop** [comment]
Thanks.

The only thing is that the first column of lines 2198-2204 should remain as it was. That's a standard used in the docs, e.g. https://feathers-plus.github.io/v1/feathers-hooks-common/index.html#populate .

Either you can make the changes, or I'll merge your changes and then fix it up.

**Comment by eddyystop** [comment]
Many thanks.

**Comment by bertho-zero** [comment]
`ignoreDefaults` don't have default value.

**Comment by eddyystop** [comment]
Thanks. I removed the default from the docs. Published it.

**Pull request merged**
